### ISSUE TITLE
id-conversions

### ISSUE THREAD

**Issue by JustusAdam** [nikita-volkov/conversion#1]
I really like your library idea. I had drafted up something similar, though smaller in scope for conversions from and to Text already.

One thing I think this would vastly benefit from were to add instances for what I'd call "id-conversions", that is conversions from type a back to the same type a.

This allows me (for example) to define functions such as this:

``` hs
(~>) ∷ (Conversion t Text, ToMustache m) ⇒ t → m → (Text, MustacheValue)
(~>) t = (convert t,) . toMustache
```

Without having to also another function for converting if the source string was text.

I'll draft up a pull request for the necessary changes. Unless you'd like to do this yourself.

**Comment by nikita-volkov** [comment]
Good example. Thanks. I'll merge the PR.
